menu:
    Blog: /
    Archive: /archives/
    #Weibo: http://weibo.com/cccccolor
    GitHub: https://github.com/nickeyme
    #Rss: /atom.xml

favicon: /favicon.jpg
logo: /favicon.jpg

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2021